name: CI build

on: [push]

jobs:
  build_apache2_wsgi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Retrieve Version from version.py"
      run: |
        echo TAG_NAME=$(cat acme_srv/version.py | grep -i __version__ | head -n 1 | sed 's/__version__ = //g' | sed s/\'//g) >> $GITHUB_ENV

    - run: echo "Repo is at version ${{ steps.acme2certifier_ver.outputs.tag }}"
    - run: echo "Latest tag is ${{ env.TAG_NAME }}"

    - run: echo "Rund build workflow for commit ${{ github.sha }}"

    - name: "Create image"
      run: |
        cat examples/Docker/apache2/wsgi/Dockerfile | docker build -t acme2certifier/wsgi -t grindsa/acme2certifier:apache2-wsgi -t grindsa/acme2certifier:${{ env.TAG_NAME }}-apache2-wsgi -t ghcr.io/grindsa/acme2certifier:apache2-wsgi -t ghcr.io/grindsa/acme2certifier:${{ env.TAG_NAME }}-apache2-wsgi -f - . --no-cache

    - name: "Dump image to local filesystem"
      run: |
          mkdir -p /tmp/a2c-artificats
          docker save acme2certifier/wsgi:latest -o /tmp/a2c-artificats/a2c-apache2-wsgi.tar
          gzip /tmp/a2c-artificats/a2c-apache2-wsgi.tar

    - uses: actions/upload-artifact@v3
      with:
        name: a2c-apache2-wsgi.tar.gz
        path: /tmp/a2c-artificats/a2c-apache2-wsgi.tar.gz

  build_apache2_django:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Retrieve Version from version.py"
      run: |
        echo TAG_NAME=$(cat acme_srv/version.py | grep -i __version__ | head -n 1 | sed 's/__version__ = //g' | sed s/\'//g) >> $GITHUB_ENV

    - run: echo "Repo is at version ${{ steps.acme2certifier_ver.outputs.tag }}"
    - run: echo "Latest tag is ${{ env.TAG_NAME }}"

    - run: echo "Rund build workflow for commit ${{ github.sha }}"

    - name: "Create image"
      run: |
          cat examples/Docker/apache2/django/Dockerfile | docker build -t acme2certifier/django -t grindsa/acme2certifier:apache2-django -t grindsa/acme2certifier:${{ env.TAG_NAME }}-apache2-django -t ghcr.io/grindsa/acme2certifier:apache2-django -t ghcr.io/grindsa/acme2certifier:${{ env.TAG_NAME }}-apache2-django -f - .  --no-cache

    - name: "Dump image to local filesystem"
      run: |
          mkdir -p /tmp/a2c-artificats
          docker save acme2certifier/django:latest -o /tmp/a2c-artificats/a2c-apache2-django.tar
          gzip /tmp/a2c-artificats/a2c-apache2-django.tar

    - uses: actions/upload-artifact@v3
      with:
        name: a2c-apache2-django.tar.gz
        path: /tmp/a2c-artificats/a2c-apache2-django.tar.gz

  build_nginx_wsgi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Retrieve Version from version.py"
      run: |
        echo TAG_NAME=$(cat acme_srv/version.py | grep -i __version__ | head -n 1 | sed 's/__version__ = //g' | sed s/\'//g) >> $GITHUB_ENV

    - run: echo "Repo is at version ${{ steps.acme2certifier_ver.outputs.tag }}"
    - run: echo "Latest tag is ${{ env.TAG_NAME }}"

    - run: echo "Rund build workflow for commit ${{ github.sha }}"

    - name: "Create image"
      run: |
           cat examples/Docker/nginx/wsgi/Dockerfile | docker build -t acme2certifier/wsgi -t grindsa/acme2certifier:nginx-wsgi -t grindsa/acme2certifier:${{ env.TAG_NAME }}-nginx-wsgi -t ghcr.io/grindsa/acme2certifier:nginx-wsgi -t ghcr.io/grindsa/acme2certifier:${{ env.TAG_NAME }}-nginx-wsgi -f - . --no-cache

    - name: "Dump image to local filesystem"
      run: |
          mkdir -p /tmp/a2c-artificats
          docker save acme2certifier/wsgi:latest -o /tmp/a2c-artificats/a2c-nginx-wsgi.tar
          gzip /tmp/a2c-artificats/a2c-nginx-wsgi.tar

    - uses: actions/upload-artifact@v3
      with:
        name: a2c-nginx-wsgi.tar.gz
        path: /tmp/a2c-artificats/a2c-nginx-wsgi.tar.gz

  build_nginx_django:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Retrieve Version from version.py"
      run: |
        echo TAG_NAME=$(cat acme_srv/version.py | grep -i __version__ | head -n 1 | sed 's/__version__ = //g' | sed s/\'//g) >> $GITHUB_ENV

    - run: echo "Repo is at version ${{ steps.acme2certifier_ver.outputs.tag }}"
    - run: echo "Latest tag is ${{ env.TAG_NAME }}"

    - run: echo "Rund build workflow for commit ${{ github.sha }}"

    - name: "Create image"
      run: |
          cat examples/Docker/nginx/django/Dockerfile | docker build -t acme2certifier/django -t grindsa/acme2certifier:nginx-django -t grindsa/acme2certifier:${{ env.TAG_NAME }}-nginx-django -t ghcr.io/grindsa/acme2certifier:nginx-django -t ghcr.io/grindsa/acme2certifier:${{ env.TAG_NAME }}-nginx-django -f - .  --no-cache

    - name: "Dump image to local filesystem"
      run: |
          mkdir -p /tmp/a2c-artificats
          docker save acme2certifier/django:latest -o /tmp/a2c-artificats/a2c-nginx-django.tar
          gzip /tmp/a2c-artificats/a2c-nginx-django.tar

    - uses: actions/upload-artifact@v3
      with:
        name: a2c-nginx-django.tar.gz
        path: /tmp/a2c-artificats/a2c-nginx-django.tar.gz

  build_rpm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Retrieve Version from version.py"
      run: |
        echo TAG_NAME=$(cat acme_srv/version.py | grep -i __version__ | head -n 1 | sed 's/__version__ = //g' | sed s/\'//g) >> $GITHUB_ENV

    - run: echo "Repo is at version ${{ steps.acme2certifier_ver.outputs.tag }}"
    - run: echo "Latest tag is ${{ env.TAG_NAME }}"

    - name: update version number in spec file
      run: |
        sudo sed -i "s/__version__/${{ env.TAG_NAME }}/g" examples/install_scripts/rpm/acme2certifier.spec
        sudo sed -i "s/\/var\/www\/acme2certifier\/volume/\/etc\/nginx/g" examples/nginx/nginx_acme_srv_ssl.conf
        git config --global user.email "grindelsack@gmail.com"
        git config --global user.name "rpm update"
        git add examples/nginx
        git commit -a -m "rpm update"

    - name: Build RPM package
      id: rpm_build
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "examples/install_scripts/rpm/acme2certifier.spec"

    - uses: actions/upload-artifact@v3
      with:
        name: acme2certifier-${{ env.TAG_NAME }}-1.0.noarch.rpm
        path: ${{ steps.rpm_build.outputs.rpm_dir_path }}noarch/acme2certifier-${{ env.TAG_NAME }}-1.0.noarch.rpm

  build_deb:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Retrieve Version from version.py"
      run: |
        echo TAG_NAME=$(cat acme_srv/version.py | grep -i __version__ | head -n 1 | sed 's/__version__ = //g' | sed s/\'//g) >> $GITHUB_ENV

    - run: echo "Repo is at version ${{ steps.acme2certifier_ver.outputs.tag }}"
    - run: echo "Latest tag is ${{ env.TAG_NAME }}"

    - name: Prepare deb packaging environment
      run: |
        sudo apt-get -y install build-essential fakeroot dpkg-dev devscripts debhelper
        rm setup.py
        cp -R examples/install_scripts/debian ./
        sudo sed -i "s/__version__/${{ env.TAG_NAME }}/g" debian/changelog
        cd ../
        tar cvfz ../acme2certifier_${{ env.TAG_NAME }}.orig.tar.gz ./

    - name: "Build debian package"
      run: |
        dpkg-buildpackage -uc -us
        cp ../acme2certifier_${{ env.TAG_NAME }}-1_all.deb "$(pwd)/acme2certifier_${{ env.TAG_NAME }}-1_all.deb"

    - uses: actions/upload-artifact@v3
      with:
        name: acme2certifier_${{ env.TAG_NAME }}-1_all.deb
        path: acme2certifier_${{ env.TAG_NAME }}-1_all.deb