name: CI build

on: [push]

jobs:
  build_apache2_wsgi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo "Rund build workflow for commit ${{ github.sha }}"

    - name: "Create image"
      run: |
        cat examples/Docker/apache2/wsgi/Dockerfile | docker build -t acme2certifier/wsgi -t grindsa/acme2certifier:apache2-wsgi -f - . --no-cache

    - name: "Dump image to local filesystem"
      run: |
          mkdir -p /tmp/a2c-artificats
          docker save acme2certifier/wsgi:latest -o /tmp/a2c-artificats/a2c-wsgi.tar
          gzip /tmp/a2c-artificats/a2c-wsgi.tar

    - uses: actions/upload-artifact@v3
      with:
        name: a2c-wsgi.tar.gz
        path: /tmp/a2c-artificats/a2c-wsgi.tar.gz
