# .github/workflows/first_cd.yml
name: First Continuous Deployment

on:
  push:
    branches:
      - develop
jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      src:
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - 'firstpath/**'
  do_something:
    needs: check_changes
    if: needs.check_changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    steps:
        run: echo "do something"