name: ci-build

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: echo "Build-1"
    - run: echo "Latest tag is ${{ github.run_id }}"

    - name: "Sleep for 5s"
      uses: juliangruber/sleep-action@v2.0.3
      with:
        time: 5s

    - run: echo "Latest tag is ${{ github.run_id }}"
    - run: echo "SHA ${{ github.sha }}"

    - name: "Create artifact"
      id: create_artifcat
      run: |
        mkdir -p ${{ github.workspace }}/artifact/upload
        touch ${{ github.workspace }}/artifact/upload/artifact.${{ github.run_id }}.txt
        echo "Hello world" > ${{ github.workspace }}/artifact/upload/artifact.${{ github.run_id }}.txt
        echo "${{ github.run_id }}" >> ${{ github.workspace }}/artifact/upload/artifact.${{ github.run_id }}.txt
        echo "${{ github.ref }}" >> ${{ github.workspace }}/artifact/upload/artifact.${{ github.run_id }}.txt
        echo "artifact build successful"
        cat ${{ github.workspace }}/artifact/upload/artifact.${{ github.run_id }}.txt

    - name: "Upload Artifact"
      uses: actions/upload-artifact@master
      with:
        name: artifact.${{ github.run_id }}.txt
        path: ${{ github.workspace }}/artifact/upload/

    - name: Trigger next workflow
      if: success()
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: deploy-event
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "run_id": "${{ github.run_id }}"}'
