name: CI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo "Rund build workflow"

    - name: "[ WAIT ] Sleep for 10s"
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - run: echo ${{ github.ref }}
    - run: echo ${{ github.sha }}

    - run: echo "Rund build workflow ended"