name: CI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo "Rund build workflow for commit ${{ github.sha }}"

    - name: "Create images"
      run: |
        cat examples/Docker/apache2/wsgi/Dockerfile | docker build -t grindsa/acme2certifier:apache2-wsgi -f - . --no-cache

    - name: "Dump images to local filesystem"
      run: |
          docker save grindsa/acme2certifier:apache2-wsgi -o ac2-wsgi.tar


    - run: echo "Rund build workflow ended"