name: CI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo "Rund build workflow for commit ${{ github.sha }}"

    - name: "Create images"
      run: |
        exit 1
        cat examples/Docker/apache2/wsgi/Dockerfile | docker build -t grindsa/acme2certifier:apache2-wsgi -f - . --no-cache

    - name: "Dump images to local filesystem"
      run: |
          mkdir -p /tmp/a2c-artificats
          docker save grindsa/acme2certifier:apache2-wsgi -o /tmp/a2c-artificats/ac2-wsgi-${{ github.sha }}.tar
          gzip /tmp/a2c-artificats/ac2-wsgi-${{ github.sha }}.tar

    - uses: actions/upload-artifact@v3
      with:
        name: ac2-wsgi-${{ github.sha }}.tar.gz
        path: /tmp/a2c-artificats/ac2-wsgi-${{ github.sha }}.tar.gz


    - run: echo "Rund build workflow ended"