name: CI deploy # Change the name of the workflow to CI deploy

on:
  workflow_run:
    workflows: [CI build]
    types:
      - completed

jobs:

  success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The First workflow completed successfully.'

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo "deploy-1"
    - run: echo "Latest tag is ${{ github.run_id }}"
    - run: echo "SHA is ${{ github.sha }}"