name: CI deploy

on:
  pull_request:
    branches:
      - foo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo "deploy-1"
    - run: echo "Latest tag is ${{ github.run_id }}"
    - run: echo "SHA is ${{ github.sha }}"



