name: "deploy-1" # Change the name of the workflow to CI deploy

on:
  repository_dispatch:
    types: [deploy-event]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo "deploy-1"
    - run: echo "run_id is ${{ github.run_id }}"
    - run: echo "run.id is ${{ github.event.workflow_run.id }}"
    - run: echo "Remote run_id is ${{ github.event.client_payload.run_id }}"
    - run: echo "Remote SHA is ${{ github.event.client_payload.sha }}"
    - run: echo "Remote Ref is ${{ github.event.client_payload.ref }}"
    - run: echo "SHA is ${{ github.sha }}"