name: CI Test

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3

    - run: echo "Run test workflow for commit ${{ github.sha }}"

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        github_token: ${{secrets.GITHUB_TOKEN}}
        name: a2c-wsgi.tar.gz
        path: /tmp

    - name: Load Docker images into repository
      working-directory: /tmp
      run: |
        gunzip a2c-wsgi.tar.gz
        docker load -i a2c-wsgi.tar
        docker images

    - name: "Bring up container"
      working-directory: examples/Docker/
      run: |
        sudo mkdir -p data
        docker network create acme
        docker-compose up -d
        docker-compose logs

    - name: Load Docker images into repository
      working-directory: /tmp
      run: |
        docker images